# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Codecademy "Deploy a Website"
email: info@sofim.ch
description: > # this means to ignore newlines until "baseurl:"
gratiskurs mit jekyll (ruby 2.2.x) & github-deployment. dns via eigene verwaltung
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hpsof.sofim.com" # the base hostname & protocol for your site
twitter_username: hpsof
github_username:  hpsof

# Build settings
markdown: kramdown
